# ==========================================
# CONFIGURACIÓN DEL SERVIDOR
# ==========================================
server.port=8080
spring.application.name=api-gateway

# Java 21: Habilitar Hilos Virtuales para máxima concurrencia
spring.threads.virtual.enabled=true

# ==========================================
# CONFIGURACIÓN CORS (Para tu React en puerto 3000)
# ==========================================
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true

# ==========================================
# RUTAS DE MICROSERVICIOS
# ==========================================

# 1. Servicio de Login / Auth (Puerto 8081)
# Ahora escucha en /api/auth/** y quita el primer segmento (/api)
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

# 2. Servicio SIGER - Core (Puerto 8082)
spring.cloud.gateway.server.webflux.routes[1].id=siger-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/siger/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=2

# 3. Servicio SGS - Seguimiento (Puerto 8083)
spring.cloud.gateway.server.webflux.routes[2].id=sgs-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/sgs/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=2

# 4. Servicio PRO NIÑEZ - IA (Puerto 8084)
spring.cloud.gateway.server.webflux.routes[3].id=proninez-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/proninez/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=2

# ==========================================
# CONFIGURACIÓN DE SEGURIDAD (JWT SIMÉTRICO)
# ==========================================
# Comentado porque usamos validación simétrica en el SecurityConfig
# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/auth/oauth2/jwks

# Clave secreta compartida (SGS, Auth y Gateway)
jwt.secret=DefensoriaSmid2026SecretKeyHS256!